# Generated by Django 2.2.2 on 2019-06-16 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام کالای مورد نظر را وارد کنید', max_length=30, verbose_name='نام کالا')),
                ('info', models.CharField(help_text='درباره ی کالای مورد نظر توضیحاتی وارد کنید', max_length=100, verbose_name='درباره کالا')),
                ('link', models.CharField(help_text='لینک درگاه خرید محصول را وارد کنید', max_length=100, verbose_name='لینک خرید محصول')),
                ('price', models.IntegerField(blank=True, default='100', help_text='قیمت محصول مورد نظر را وارد کنید', verbose_name='قیمت')),
                ('status', models.CharField(choices=[('a', 'موجود'), ('u', 'ناموجود'), ('d', 'تخفیف')], default='y', help_text='وضعیت محصول', max_length=1, verbose_name='وضعیت محصول')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price'],
                'verbose_name_plural': 'محصولات',
                'permissions': (('can_mark_returned', 'set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='این یک متن راهنما برای موضوع است', max_length=100, verbose_name='موضوع')),
                ('text', models.TextField(help_text='در کادر بالا باید متن و یا ممحتویات پستتون رو بنویسید', max_length=500, verbose_name='متن پست')),
                ('pub_date', models.DateField(help_text='تاریخ انتشار این پست را وارد کنید', verbose_name='تاریخ انتشار')),
                ('image', models.ImageField(default='/home/mostafa/Pictures/1.png', help_text='عکس پست را آپلود کنید', upload_to='', verbose_name='تصویر پست')),
                ('bol', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pub_date'],
                'verbose_name_plural': 'پست ها',
                'permissions': (('can_mark_returned', 'set book as returned'),),
            },
        ),
    ]
