# Generated by Django 2.2.2 on 2019-06-16 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the item you are interested in', max_length=30, verbose_name='Product Name')),
                ('info', models.CharField(help_text='Enter a description for the item you are looking for', max_length=100, verbose_name='Product Info')),
                ('link', models.CharField(help_text='Enter product purchase link', max_length=100, verbose_name='Product Download Link')),
                ('price', models.IntegerField(blank=True, default='100', help_text='Enter the price of the product you are looking for', verbose_name='Price')),
                ('status', models.CharField(choices=[('a', 'Available'), ('u', 'unavailable'), ('d', 'Discount')], default='y', help_text='Choice Product status', max_length=1, verbose_name='Product Status')),
                ('author', models.ForeignKey(help_text='Choose Your User name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price'],
                'verbose_name_plural': 'Products',
                'permissions': (('can_mark_returned', 'set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='This is a help text for the subject', max_length=100, verbose_name='Title')),
                ('text', models.TextField(help_text='In the box above, you must write the text or contents of your post', max_length=500, verbose_name='Post Text')),
                ('pub_date', models.DateField(help_text='Enter the release date of this post', verbose_name='Pub Date')),
                ('image', models.ImageField(default='/home/mostafa/Pictures/1.png', help_text='Upload Post Image', upload_to='', verbose_name='Upload Image')),
                ('author', models.ForeignKey(help_text='Choose Your User name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pub_date'],
                'verbose_name_plural': 'Posts',
                'permissions': (('can_mark_returned', 'set book as returned'),),
            },
        ),
    ]
